spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/qq?serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #配置监控统计拦截的filters,去掉后监控界面sql将无法统计,"wall"用于防火墙
    filter: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache,并且指定每个连接PSCache的大小

    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    #通过connectionProperties属性来打开mergeSql功能;慢sql记录
   # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableldleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。
    validationQuery: select 1 from dual
    #建议配置为true，不影响性能，并且保证安全性。
    #申请连接的时候检测，如果空闲时间大于
    #timeBetweenEvictionRunsMillis，
    #执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testonReturn: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

