spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qq?serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

jpa:
  database: Mysql
  show-sql: true
  hibernate:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy